### ISSUE TITLE
Scalajs yaml support

### ISSUE THREAD

**Issue by Angel-O** [outr/profig#82]
Profig used support yaml configuration files for scalajs applications.

I was wondering: why was it dropped on the latest versions ?
Are there plans to bring it back?

Thank you.

**Comment by darkfrog26** [comment]
Well, I dropped direct support for Yaml in favor of the support that Fabric (my new JSON library) offers, but it's JVM-only.  If I recall, the Scala.js YAML support was only at compile-time conversion to JSON that is loaded into the JavaScript generated. Is this what you mean?

**Comment by Angel-O** [comment]
Hi @darkfrog26 

I am not 100% sure about converting to JSON at compile time: I've never used it for that specific use case. 

I am using it to map configuration from a `yml` file to scala case classes in a scala.js app as you would do with `pureconfig` in the JVM world (except for default variables and the format being `yml` instead of `hocon`)

For instance [this](https://github.com/Angel-O/issue-board/blob/main/front-end/src/main/resources/application.yaml) is an example of the configuration file and [this](https://github.com/Angel-O/issue-board/blob/main/front-end/src/main/scala/com/angelo/dashboard/AppConfig.scala) is how I am loading that same configuration at runtime

Haven't used Fabric before, are you planning to add support for scala.js ? 

That's really the platform I need a config library for. I tried a few different ones, but couldn't find a library with a nice api with little boilerplate and ideally the ability to set default values.

**Comment by darkfrog26** [comment]
Fabric fully supports Scala.js, but I don't think anything supports reading YAML in JavaScript (hence the need to convert to JSON), so the XML, YAML, etc. support is JVM-specific. I supported this in previous versions of Profig via a compile-time Macro that would pick up all resource files, convert them into static JSON, and then inject them into the JavaScript so they would be accessible at runtime. However, it was a bit overly complicated and problematic to support Scala 3.

If there's no other solution that works for you, I can probably add the support back for this feature pretty easily. However, let's discuss some alternatives first to see if we can avoid that:

1.) Have you considered just using JSON instead of YAML? I know it's not as concise, but it's a more consistent standard.
2.) What about sending the configuration from the server instead of injecting it? This is likely a more secure route and would get around any issues.

Let me know if neither of those are acceptable solutions and I'll see about getting the support added back in.

**Comment by Angel-O** [comment]
Yup, makes sense 🚀  will take a look when I get some time.

**Comment by darkfrog26** [comment]
@Angel-O any updates on this or should I close it?

**Comment by Angel-O** [comment]
@darkfrog26 apologies, just seen this. I'll pull the latest version and report back today after work.

**Comment by Angel-O** [comment]
@darkfrog26 how hard would it be to bring back yaml support ? if it's too much work, don't worry: go ahead and close this issue. Thanks for looking into it !

**Comment by darkfrog26** [comment]
It's non trivial to add it back as it would need to rely on compile-time parsingj.
